"""initial schema

Revision ID: e3fe5fcf3e90
Revises: 
Create Date: 2026-07-16 08:50:53.856789

"""
from typing import Sequence, Union
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3fe5fcf3e90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asanclipproducts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rag_text', sa.Text(), nullable=True),
    sa.Column('product_type', sa.Text(), nullable=True),
    sa.Column('occasion', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('tag_status', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asanclipproducts_id'), 'asanclipproducts', ['id'], unique=False)
    op.create_table('firewall_daily_usage',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('used_units', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_index(op.f('ix_firewall_daily_usage_day'), 'firewall_daily_usage', ['day'], unique=False)
    op.create_table('product_captions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('caption_text', sa.Text(), nullable=False),
    sa.Column('caption_type', sa.String(length=50), nullable=False),
    sa.Column('occasion_category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pc_product_active', 'product_captions', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_product_captions_caption_type'), 'product_captions', ['caption_type'], unique=False)
    op.create_index(op.f('ix_product_captions_id'), 'product_captions', ['id'], unique=False)
    op.create_index(op.f('ix_product_captions_is_active'), 'product_captions', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_captions_occasion_category'), 'product_captions', ['occasion_category'], unique=False)
    op.create_index(op.f('ix_product_captions_product_id'), 'product_captions', ['product_id'], unique=False)
    op.create_table('retrieval_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('query_raw', sa.Text(), nullable=False),
    sa.Column('query_normalized', sa.Text(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_length', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('block_reason', sa.String(length=128), nullable=True),
    sa.Column('firewall_allowed', sa.Boolean(), nullable=True),
    sa.Column('firewall_reason', sa.String(length=128), nullable=True),
    sa.Column('firewall_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('query_validation_score', sa.Float(), nullable=True),
    sa.Column('semantic_best_field', sa.String(length=64), nullable=True),
    sa.Column('semantic_best_score', sa.Float(), nullable=True),
    sa.Column('semantic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('route_reason', sa.String(length=128), nullable=True),
    sa.Column('retrieval_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieval_quality_score', sa.Float(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('bm25_used', sa.Boolean(), nullable=True),
    sa.Column('retry_triggered', sa.Boolean(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('attempt_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('top_result_id', sa.BigInteger(), nullable=True),
    sa.Column('top_result_score', sa.Float(), nullable=True),
    sa.Column('top_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_total_ms', sa.Float(), nullable=True),
    sa.Column('latency_firewall_ms', sa.Float(), nullable=True),
    sa.Column('latency_preprocess_ms', sa.Float(), nullable=True),
    sa.Column('latency_metadata_ms', sa.Float(), nullable=True),
    sa.Column('latency_semantic_ms', sa.Float(), nullable=True),
    sa.Column('latency_embedding_ms', sa.Float(), nullable=True),
    sa.Column('latency_candidate_ms', sa.Float(), nullable=True),
    sa.Column('latency_retrieval_ms', sa.Float(), nullable=True),
    sa.Column('latency_ranking_ms', sa.Float(), nullable=True),
    sa.Column('latency_alignment_ms', sa.Float(), nullable=True),
    sa.Column('cost_allowed', sa.Boolean(), nullable=True),
    sa.Column('cost_reason', sa.String(length=128), nullable=True),
    sa.Column('cost_units', sa.Float(), nullable=True),
    sa.Column('used_today', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('estimated_input_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('cache_layer', sa.String(length=32), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_logs_blocked'), 'retrieval_logs', ['blocked'], unique=False)
    op.create_index('ix_retrieval_logs_cache', 'retrieval_logs', ['cache_hit', 'created_at'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_cache_hit'), 'retrieval_logs', ['cache_hit'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_created_at'), 'retrieval_logs', ['created_at'], unique=False)
    op.create_index('ix_retrieval_logs_created_blocked', 'retrieval_logs', ['created_at', 'blocked'], unique=False)
    op.create_index('ix_retrieval_logs_created_mode', 'retrieval_logs', ['created_at', 'mode'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_id'), 'retrieval_logs', ['id'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_mode'), 'retrieval_logs', ['mode'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_query_hash'), 'retrieval_logs', ['query_hash'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_request_id'), 'retrieval_logs', ['request_id'], unique=True)
    op.create_index(op.f('ix_retrieval_logs_retrieval_quality_score'), 'retrieval_logs', ['retrieval_quality_score'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_session_id'), 'retrieval_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_top_result_id'), 'retrieval_logs', ['top_result_id'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_user_id'), 'retrieval_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_logs_user_id'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_top_result_id'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_session_id'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_retrieval_quality_score'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_request_id'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_query_hash'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_mode'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_id'), table_name='retrieval_logs')
    op.drop_index('ix_retrieval_logs_created_mode', table_name='retrieval_logs')
    op.drop_index('ix_retrieval_logs_created_blocked', table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_created_at'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_cache_hit'), table_name='retrieval_logs')
    op.drop_index('ix_retrieval_logs_cache', table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_blocked'), table_name='retrieval_logs')
    op.drop_table('retrieval_logs')
    op.drop_index(op.f('ix_product_captions_product_id'), table_name='product_captions')
    op.drop_index(op.f('ix_product_captions_occasion_category'), table_name='product_captions')
    op.drop_index(op.f('ix_product_captions_is_active'), table_name='product_captions')
    op.drop_index(op.f('ix_product_captions_id'), table_name='product_captions')
    op.drop_index(op.f('ix_product_captions_caption_type'), table_name='product_captions')
    op.drop_index('ix_pc_product_active', table_name='product_captions')
    op.drop_table('product_captions')
    op.drop_index(op.f('ix_firewall_daily_usage_day'), table_name='firewall_daily_usage')
    op.drop_table('firewall_daily_usage')
    op.drop_index(op.f('ix_asanclipproducts_id'), table_name='asanclipproducts')
    op.drop_table('asanclipproducts')
    # ### end Alembic commands ###
